fos_rest:
    routing_loader: false
    format_listener:
        rules:
            # 1. El portero SOLO trabaja en la zona de la API (exigiendo JSON)
            - { path: '^/api', prefer_extension: true, fallback_format: json, priorities: ['json', 'html'] }
            
            # 2. PARA TODO LO DEMÁS (Profiler, barra de herramientas, etc)... ¡Se apaga!
            - { path: '^/', stop: true }